### ISSUE TITLE
Test-time augmentation: noise, blur, brightness, contrast, geometric scaling, etc.

### ISSUE THREAD

**Issue by remtav** [NRCan/geo-deep-learning#106]
Wouldn't trained models gain robustness if data augmentations (utils/augmentation.py) included brightness and contrast shifts (ex.: random, 10-15%)? I imagine it could also help with overfitting issues.

**Comment by mpelchat04** [comment]
That's true for satellite imagery. But since brightness and contrast shifts are only histograms modifications, there are a few considerations:   
1. EO data other than satellite or aerial imagery (e.g. derived products from DEMs [Slope, aspect, etc.]) have specific data range and I'm not convinced that messing with these histograms would really help.  
1. We could add this feature as a parameter in the config file. But we would have to be able to turn it on/off for each band. For example, let say we use as input data images with RGB+slope. We'd like to apply contrast and/or brightness shifts on the RGB bands but probably not on the slope band...  
1. We would probably have to manage those functions ourselves, since data augmentations libraries such as [Albumentations](https://github.com/albu/albumentations) only manage 3bands data (for now).  

It's worth the discussion, tough. I think the first step would be to test the first hypothesis and work from there. I'll add this to our "tests wishlist". 

Math

**Comment by remtav** [comment]
Duplicate of #132

**Comment by remtav** [comment]
This implementation good be a good start:
https://github.com/SpaceNetChallenge/SpaceNet_SAR_Buildings_Solutions/blob/master/2-MaksimovKA/predict/tta.py
