### ISSUE TITLE
Manage discontinuities when classifying

### ISSUE THREAD

**Issue by ymoisan** [NRCan/geo-deep-learning#11]
When classifying images, we can see linear artifacts in the final output due to the moving window used to assign classes being smaller than the image to be classified. An example: 

![image](https://user-images.githubusercontent.com/7468595/46153678-9ef02080-c241-11e8-96a2-c68da52b618f.png)
 
The solution would be to manage the moving window overlap and get the mean value of the prediction for overlapping regions. See [Audebert et al., (2016)](https://arxiv.org/abs/1609.06846)

**Comment by mpelchat04** [comment]
# Problem
The reason for these artifacts is that we need to tile the image, in order to fit it into memory and classify it. For a good pixel classification, the model rely on the context of the pixel. At the border of the tile, the model doesn't have any context to classify the pixel, giving results as shown above. 
# Solution
The idea is to find the number of pixel needed for context and write only the pixels with enough context, in the tile. To ensure that each pixel i correctly classified, each tile will overlap it's neighbors by the number of pixel required for context.  
The number of pixel required for context is depending on the depth of the model. Every time there is a resampling in the model, we add more context to the classification. Given that resampling are kernel of size 2x2, the number of pixels used for context can be obtained by 2**n where n is the depth of the model (number of times resample is done).
