### ISSUE TITLE
Capacity to choose the channels of input images

### ISSUE THREAD

**Issue by mpelchat04** [NRCan/geo-deep-learning#31]
Let say you have a 4 channels images (R+G+B+NIR), it would be nice to be able to specify only the channels you're interested in instead of having to process the image and store it with the channels you want to test. .
The channel choice should be a parameter in the yaml config file.   Linked to #56.

**Comment by ymoisan** [comment]
That means we should find a way to store channel metadata in the files to begin with.  We cannot just rely on a simple ordinal channel numbers mapping to channel wavelengths especially for high dimensionality datasets comprising derived products.  That way we could specify 'NIR' or 'slope' in the yaml and query the file to get the corresponding channel number.

**Comment by ymoisan** [comment]
We should use [rasterio](https://github.com/mapbox/rasterio).  A bunch of info follows.

> NOTE : the latest versions of rasterio are only available on \*NIX.  As of Jan. 2019
**conda install -c conda-forge rasterio** will bring  v. 0.36.0 on Windows vs 1.0.13 on \*NIX

```Python
import rasterio
# Open a connection on a GTiff file on a public S3 repo; of course `open` can read files.  
# Very interesting in the context of a WCS service ...
oam_denver = rasterio.open(
'https://oin-hotosm.s3.amazonaws.com/5bc9fe17f104840007c66503/0/5bc9fe17f104840007c66513.tif')
type(oam_denver)
<class 'rasterio.io.DatasetReader'>

# 'name' attribute of the DatasetReader object
oam_denver.name
'https://oin-hotosm.s3.amazonaws.com/5bc9fe17f104840007c66503/0/5bc9fe17f104840007c66513.tif'

# 'profile' attribute of the DatasetReader object; 'count' relates to number of bands
oam_denver.profile
{'driver': 'GTiff', 'dtype': 'uint8', 'nodata': None, 'width': 10560, 'height': 10560, 'count': 4,
'crs': CRS({'proj': 'lcc', 'lat_1': 38.45, 'lat_2': 39.75, 'lat_0': 37.83333333333334,
'lon_0': -105.5, 'x_0': 914401.8288999998, 'y_0': 304800.6096000001, 'ellps': 'GRS80',
'units': 'us-ft', 'no_defs': True}),'transform': Affine(0.25, 0.0, 3149312.0, 0.0, -0.25, 1702952.0),
'blockxsize': 512,'blockysize': 512, 'tiled': True, 'compress': 'deflate', 'interleave': 'pixel'}

# The bands
oam_denver.indexes
(1, 2, 3, 4)

# tags (metadata) of the DatasetReader object (whole file)
oam_denver.tags()
{'AREA_OR_POINT': 'Area', 'TIFFTAG_DATETIME': '2016:11:22 16:21:53',
'TIFFTAG_RESOLUTIONUNIT': '2 (pixels/inch)', 'TIFFTAG_SOFTWARE': 'Adobe Photoshop CS5 Windows',
 'TIFFTAG_XRESOLUTION': '72', 'TIFFTAG_YRESOLUTION': '72'}

# tags (metadata) of BAND 1 only
oam_denver.tags(1)
{'STATISTICS_MAXIMUM': '255', 'STATISTICS_MEAN': '129.2801815653',
'STATISTICS_MINIMUM': '36', 'STATISTICS_STDDEV': '29.821752961359'}

# Read only bands 1 and 4 separately
band1 = oam_denver.read(1)
type(band1)
<class 'numpy.ndarray'>
band1
array([[182, 185, 185, ..., 144, 149, 150],
       [184, 186, 184, ..., 148, 150, 152],
       [184, 184, 186, ..., 149, 148, 150],
       ...,
       [150, 148, 150, ..., 149, 151, 153],
       [141, 150, 150, ..., 142, 148, 148],
       [150, 151, 147, ..., 141, 141, 143]], dtype=uint8)
band1.shape
(10560, 10560)
band4 = oam_denver.read(4)
band4.shape
(10560, 10560)
# Read bands 1 and 4 at once using an array of band numbers
bands14 = oam_denver.read([1,4])
bands14.shape
(2, 10560, 10560)
bands14
array([[[182, 185, 185, ..., 144, 149, 150],
        [184, 186, 184, ..., 148, 150, 152],
        [184, 184, 186, ..., 149, 148, 150],
        ...,
        [150, 148, 150, ..., 149, 151, 153],
        [141, 150, 150, ..., 142, 148, 148],
        [150, 151, 147, ..., 141, 141, 143]],

       [[212, 214, 214, ..., 184, 187, 188],
        [214, 216, 214, ..., 185, 189, 193],
        [214, 214, 216, ..., 188, 186, 190],
        ...,
        [217, 212, 215, ..., 186, 187, 189],
        [212, 214, 214, ..., 182, 186, 183],
        [212, 216, 212, ..., 179, 181, 182]]], dtype=uint8)
```
The other thing we could do is use rasterio to add metadata (in rasterio parlance, [tags](https://rasterio.readthedocs.io/en/latest/topics/tags.html)) to our GTiff files and/or individual bands. Depending on metadata stored, it could allow devising a generic query mechanism e.g. to read only bands in specific spectral intervals.  

Before we write any metadata, however, we should identify whether we should use a namespace for our tags (I think we should) and if so see how we could come up with a generic way of doing that based e.g. on [ISO 19115](https://en.wikipedia.org/wiki/Geospatial_metadata).

P.S. From an operational point of view, it could be interesting to limit GTiff files to 1 channel only.  One example : "Landsat on AWS makes each band of each Landsat scene available as a stand-alone GeoTIFF and the scene’s metadata is hosted as a text file." [Accessing Landsat on AWS](https://github.com/landsat-pds/landsat_ingestor/wiki/Accessing-Landsat-on-AWS).  That requires a strict naming convention, however.  Still, this ticket is needed because GTiff files often have several image bands.

**Comment by ymoisan** [comment]
Way forward as discussed in a meeting :

- store information about data used for training **in the resulting model** directly; persistence must be done in the model for future inference
  - what info, naming convention
  - this could be done in an accompanying file (to the PyTorch model file, .pth\*), like a YAML file
- concentrate on WCS
- for Geotiff files, store only 1 channel, with a name following a convention (conventoin TBD)
- check [Fiona](https://fiona.readthedocs.io/en/latest/)

\* see interesting distinction between a *state file* like PyTorch's *.pth* files and a *model file* : [In a model file, the complete model is stored, whereas in a state file only the parameters are stored.](https://stackoverflow.com/questions/49941426/attributeerror-collections-ordereddict-object-has-no-attribute-eval/49942523#49942523)

**Comment by mpelchat04** [comment]
Irrelevant. Closing it.
