### ISSUE TITLE
Use OGC-WCS together with GeoTIFF files

### ISSUE THREAD

**Issue by ymoisan** [NRCan/geo-deep-learning#50]
[OGC-WCS](https://www.opengeospatial.org/standards/wcs) -- Web Coverage Service -- allows one to request a specific area and get a GeoTIFF response.  Since GeoTIFF is the data format used for training/inference, using a WCS would free users from having to store GeoTIFF files on their hardware.  This is turn has the benefit of easier integration to a Big Data environment that would expose its raster data sets as WCS.  We ought to make the code use GeoTIFF files generated on the fly through WCS web requests just as easy as using local GeoTIFF files.

**Comment by mpelchat04** [comment]
# Considerations:  
## User-specified informations  
- Service URL  
- Layer name  
- Bands information in WCS request (number, type, sensor, etc.)  

All those informations should be stored within the hdfs files and with the model, once the training is done. This will improve re-usability of the datasets and models. Moreover, we should store (or at least make sure to include an easy access to) the service's GetCapability result.  

## Handling the bbox for the request  
### Options:  
1. Specified by the user from a csv-like file.  
 (+) Same approach for data preparation (images_to_samples.py) or inference (inference.py).  
 (-) Substantial effort required by the user.  
 
2. AOIs are stored as polygons in the gpkg, differentiating trn/val/tst AOIs.  
 (+) Easy for the user to generate those polygons.  
 (+) Same approach for data preparation (images_to_samples.py) or inference (inference.py).  
 (++) AOIs can be stored and re-used once the model is trained. Giving context on the training process will greatly improve the model's re-usability.  
 
3. AOIs are deducted from the reference (ground truth) data. Convex hull around polygons, differentiating trn/val/tst data.  
 (+) Not much preprocessing required by the user, for data preparation.  
 (++) AOIs can be stored and re-used once the model is trained. Giving context on the training process will greatly improve the model's re-usability.
 (-) Another approach must be designed for inference, since there are usually no reference data, at that stage.

**Comment by mpelchat04** [comment]
Support for WCS in inference was implemented in my [fork](https://github.com/mpelchat04/geo-deep-learning/tree/wcs) but we decided not to continue on this track for multiple reasons. Of which:  

First, WCS might not be the best solution for what we intend to do. WCS services are very vendor specific, I believe we're more looking for a "raster data connector", in order to directly access the stored raw data, not reprocess/interpolated data. To that end, we might end up with [OPeNDAP](https://www.opendap.org) or [THREDDS](https://www.unidata.ucar.edu/software/thredds/current/tds/) services. As other options, we note [OGC API coverage] (https://github.com/opengeospatial/ogc_api_coverages) which might get more attention from the public in a near future and [STAC](https://stacspec.org/), which is getting a lot of attention these days.  

Second, [OWSLib](http://geopython.github.io/OWSLib/) does not meet our requirements yet;  
- We got issues regarding [http handling](https://github.com/geopython/OWSLib/issues/588)
- We have to handle the version negotiation
- Maxsize and other server limitations are not handled by the lib

**Comment by ymoisan** [comment]
Apparently, the [OGC Spatio-Temporal Coverage / Datacube Standards](http://myogc.org/go/coveragesDWG) -- amongst which WCS -- do not include url parameters relating to pixel size in GetCoverage operations.  [MapServer's support](https://mapserver.org/ogc/wcs_server.html#wcs-2-0-kvp-request-parameters) for those parameters is nice, but since we cannot rely on an arbitrary WCS resource to support pixel resampling, WCS as a standard to fetch raster datasets for learning or inference looses much of its value.
