### ISSUE TITLE
Mismatch between values for number of classes?

### ISSUE THREAD

**Issue by sfoucher** [NRCan/geo-deep-learning#98]
Hi there,

I was wondering why the condition:

`if len(distinct_att)+1 != num_classes:`

in file utils.py (function `validate_num_classes`). I have 5 distinct classes in my geopackage and I need to set `num_classes=6` to pass this validation.

Thank you,

Sam

**Comment by mpelchat04** [comment]
@sfoucher  
Hi Sam,  
Historically, the purpose of it was to make the user aware that a class 0 (background) will be added to the data during training and that there will be `NClasses+1` possible values for predictions afterward.   
Hence the +1 when validating.   

Might be misleading, though.  
Maybe we shouldn't give the background class much attention, since it's more of a catch-all class than a class with useful information.  
Plus, the number of classes could be directly derived from the geopackage. We actually don't need the user's input for this.

**Comment by mpelchat04** [comment]
Partially fixed with #112. 

The parameter `num_classes` is still present in the config file, but the value should be set to the number of classes present in the ground truth data (gpkg).

There are still some work needed to remove this parameter from the config file and read it directly from the gpkg file.

**Comment by victorlazio109** [comment]
This has been resolved.
